# Generated by Django 5.0.6 on 2024-06-07 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=13)),
                ('telegram_id', models.CharField(max_length=200, unique=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('language_code', models.CharField(default='uz', max_length=2)),
                ('status', models.CharField(default='bronze', max_length=200)),
                ('order_count', models.IntegerField(default=0)),
                ('last_visited_place', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=200, unique=True)),
                ('name_ru', models.CharField(max_length=200, unique=True)),
                ('name_en', models.CharField(max_length=200, unique=True)),
                ('photo', models.CharField(max_length=200)),
                ('has_subcategory', models.BooleanField(default=False)),
                ('belongs_to', models.CharField(max_length=200)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='api.category')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=200, unique=True)),
                ('name_ru', models.CharField(max_length=200, unique=True)),
                ('name_en', models.CharField(max_length=200, unique=True)),
                ('desc_uz', models.CharField(blank=True, max_length=200, null=True)),
                ('desc_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('desc_en', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('photo', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.category')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_categories', to='api.category')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=5, max_digits=12)),
                ('created_date', models.DateField()),
                ('created_time', models.TimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.telegramuser')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliver_type', models.CharField(max_length=50)),
                ('deliver_time', models.CharField(blank=True, max_length=5, null=True)),
                ('status', models.CharField(default='not_accepted', max_length=50)),
                ('created_date', models.DateField()),
                ('created_time', models.TimeField()),
                ('payment_method', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to='api.telegramuser')),
            ],
            options={
                'db_table': 'user_orders',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.CharField(max_length=200)),
                ('full_address', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='api.telegramuser')),
            ],
            options={
                'db_table': 'locations',
                'unique_together': {('user', 'full_address')},
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='api.telegramuser')),
            ],
            options={
                'db_table': 'cart',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
