# Generated by Django 5.0.6 on 2024-06-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='language_code',
            field=models.CharField(choices=[('uz', 'uz'), ('uz', 'ru'), ('uz', 'en')], default='uz', max_length=2),
        ),
    ]
