# Generated by Django 5.0.6 on 2024-06-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_telegramuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='belongs_to',
            field=models.CharField(choices=[('foods', 'Foods'), ('others', 'Others')], db_default='foods', default=(('foods', 'Foods'), ('others', 'Others')), max_length=200),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='language_code',
            field=models.CharField(choices=[('uz', 'uz'), ('ru', 'ru'), ('en', 'en')], db_default='uz', default='uz', max_length=2),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='status',
            field=models.CharField(choices=[('bronze', '🥉 Bronze'), ('silver', '🥈 Silver'), ('gold', '🥇 Gold'), ('platinum', '🌟 Platinum')], db_default='bronze', default='bronze', max_length=200),
        ),
    ]
