# Generated by Django 5.0.6 on 2024-06-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_product_subcategory_alter_category_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='deliver_type',
            field=models.CharField(choices=[('deliver', 'Delivery'), ('take away', 'Take away')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='status',
            field=models.CharField(choices=[('not_accepted', '⛔️ Not accepted'), ('accepted', '📝 Accepted'), ('pending', '🚚 On the way'), ('completed', '✅ Completed')], default='not_accepted', max_length=50),
        ),
    ]
