# Generated by Django 5.0.6 on 2024-06-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_userorder_deliver_type_alter_userorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='payment_method',
            field=models.CharField(choices=[('cash', '💸 Cash'), ('card', '💳 Card')], max_length=20),
        ),
    ]
